// Generated by CodeSpec — do not edit manually

export class Calculator {
  private state: number = 0;

  add(number: number): number {
    this.state = this.state + number;
    return this.state;
  }

  subtract(number: number): number {
    this.state = this.state - number;
    return this.state;
  }

  muliply(number: number): number {
    this.state = this.state * number;
    return this.state;
  }

  divide(number: number): number {
    if (number === 0.0) {
      throw new Error("Can not divide by 0");
    }
    this.state = this.state / number;
    return this.state;
  }
}
