import { describe, it, expect } from "vitest";
import { generateJavaScript } from "../../src/generator/javascript.js";
import {
  primitiveType,
  listType,
  mapType,
  namedType,
  optionalType,
  constraints,
  field,
  parameter,
  input,
  output,
  stateField,
  state,
  when,
  matchArm,
  match,
  set,
  call,
  returnNode,
  fail,
  emit,
  retry,
  limit,
  comment,
  action,
  invariantRule,
  invariants,
  errorDef,
  errors,
  dependencyDef,
  depends,
  module,
} from "../../src/ast/index.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Build a comprehensive sample module for snapshot testing. */
function buildSampleModule() {
  return module({
    name: "UserRegistration",
    members: [
      input({
        fields: [
          field({
            name: "email",
            fieldType: primitiveType("Email"),
            constraints: constraints({ format: "email" }),
          }),
          field({
            name: "password",
            fieldType: primitiveType("String"),
            constraints: constraints({ min: 8, max: 128 }),
          }),
          field({
            name: "nickname",
            fieldType: optionalType(primitiveType("String")),
          }),
        ],
      }),
      output({
        fields: [
          field({ name: "user", fieldType: namedType("User") }),
          field({ name: "token", fieldType: primitiveType("String") }),
        ],
      }),
      state({
        fields: [
          stateField({
            access: "READS",
            name: "users",
            fieldType: listType(namedType("User")),
          }),
          stateField({
            access: "WRITES",
            name: "sessions",
            fieldType: listType(namedType("Session")),
          }),
        ],
      }),
      errors({
        errors: [
          errorDef({
            name: "EmailAlreadyExists",
            status: 409,
            message: "A user with this email already exists",
          }),
          errorDef({
            name: "UserNotFound",
            status: 404,
            message: "The requested user was not found",
          }),
          errorDef({ name: "InternalError" }),
        ],
      }),
      action({
        name: "register",
        params: [
          parameter({ name: "email", paramType: primitiveType("Email") }),
          parameter({ name: "password", paramType: primitiveType("String") }),
        ],
        returnType: namedType("User"),
        body: [
          when({
            condition: "CALL userExists(email)",
            body: [
              fail({
                error: "EmailAlreadyExists",
                message: "A user with this email already exists",
              }),
            ],
          }),
          set({
            variable: "hashedPassword",
            value: "CALL hashPassword(password)",
          }),
          call({
            target: "createUser",
            args: ["email", "hashedPassword"],
            assignTo: "user",
          }),
          emit({ event: "UserRegistered", payload: "user" }),
          returnNode({ value: "user" }),
        ],
      }),
      invariants({
        rules: [
          invariantRule({
            kind: "ALWAYS",
            description: "Passwords are stored as hashed values",
          }),
          invariantRule({
            kind: "NEVER",
            description: "Email is shared without consent",
          }),
        ],
      }),
      depends({
        dependencies: [
          dependencyDef({
            name: "Database",
            description: "User persistence layer",
          }),
          dependencyDef({ name: "HashService" }),
        ],
      }),
    ],
  });
}

// ---------------------------------------------------------------------------
// Header
// ---------------------------------------------------------------------------

describe("JavaScript Generator: header", () => {
  it("should include the header comment", () => {
    const mod = module({ name: "Empty", members: [] });
    const code = generateJavaScript(mod);
    expect(code).toContain("// Generated by CodeSpec — do not edit manually");
  });
});

// ---------------------------------------------------------------------------
// JSDoc typedefs
// ---------------------------------------------------------------------------

describe("JavaScript Generator: typedefs", () => {
  it("should generate JSDoc typedef for INPUT", () => {
    const mod = module({
      name: "Login",
      members: [
        input({
          fields: [
            field({ name: "email", fieldType: primitiveType("Email") }),
            field({ name: "password", fieldType: primitiveType("String") }),
          ],
        }),
      ],
    });
    const code = generateJavaScript(mod);
    expect(code).toContain("@typedef {Object} LoginInput");
    expect(code).toContain("@property {string} email");
    expect(code).toContain("@property {string} password");
  });

  it("should generate JSDoc typedef for OUTPUT", () => {
    const mod = module({
      name: "Login",
      members: [
        output({
          fields: [
            field({ name: "user", fieldType: namedType("User") }),
            field({ name: "token", fieldType: primitiveType("String") }),
          ],
        }),
      ],
    });
    const code = generateJavaScript(mod);
    expect(code).toContain("@typedef {Object} LoginOutput");
    expect(code).toContain("@property {User} user");
    expect(code).toContain("@property {string} token");
  });

  it("should handle optional fields in JSDoc", () => {
    const mod = module({
      name: "Profile",
      members: [
        input({
          fields: [
            field({
              name: "nickname",
              fieldType: optionalType(primitiveType("String")),
            }),
          ],
        }),
      ],
    });
    const code = generateJavaScript(mod);
    expect(code).toContain("@property {string} [nickname]");
  });
});

// ---------------------------------------------------------------------------
// Error classes
// ---------------------------------------------------------------------------

describe("JavaScript Generator: error classes", () => {
  it("should generate error classes without type annotations", () => {
    const mod = module({
      name: "Test",
      members: [
        errors({
          errors: [
            errorDef({
              name: "NotFound",
              status: 404,
              message: "Not found",
            }),
          ],
        }),
      ],
    });
    const code = generateJavaScript(mod);
    expect(code).toContain("export class NotFoundError extends Error {");
    expect(code).toContain("constructor(message) {");
    expect(code).toContain('super(message ?? "Not found")');
    expect(code).toContain("this.status = 404;");
  });
});

// ---------------------------------------------------------------------------
// Function generation
// ---------------------------------------------------------------------------

describe("JavaScript Generator: functions", () => {
  it("should generate functions without type annotations", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "greet",
          params: [
            parameter({ name: "name", paramType: primitiveType("String") }),
          ],
          returnType: primitiveType("String"),
          body: [returnNode({ value: "name" })],
        }),
      ],
    });
    const code = generateJavaScript(mod);
    expect(code).toContain("export function greet(name) {");
    expect(code).not.toContain(": string");
    expect(code).toContain("return name;");
  });

  it("should generate JSDoc annotations on functions", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "add",
          params: [
            parameter({ name: "a", paramType: primitiveType("Int") }),
            parameter({ name: "b", paramType: primitiveType("Int") }),
          ],
          returnType: primitiveType("Int"),
          body: [returnNode({ value: "a + b" })],
        }),
      ],
    });
    const code = generateJavaScript(mod);
    expect(code).toContain("@param {number} a");
    expect(code).toContain("@param {number} b");
    expect(code).toContain("@returns {number}");
  });
});

// ---------------------------------------------------------------------------
// Statement generation
// ---------------------------------------------------------------------------

describe("JavaScript Generator: statements", () => {
  it("should generate WHEN as if statement", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "check",
          params: [
            parameter({ name: "x", paramType: primitiveType("Int") }),
          ],
          returnType: primitiveType("String"),
          body: [
            when({
              condition: "x > 0",
              body: [returnNode({ value: '"positive"' })],
              otherwise: [returnNode({ value: '"non-positive"' })],
            }),
          ],
        }),
      ],
    });
    const code = generateJavaScript(mod);
    expect(code).toContain("if (x > 0) {");
    expect(code).toContain("} else {");
  });

  it("should generate MATCH as switch statement", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "route",
          params: [
            parameter({ name: "role", paramType: primitiveType("String") }),
          ],
          returnType: primitiveType("Void"),
          body: [
            match({
              subject: "role",
              arms: [
                matchArm({
                  pattern: "admin",
                  body: [returnNode({ value: '"admin-panel"' })],
                }),
                matchArm({
                  pattern: "_",
                  body: [returnNode({ value: '"home"' })],
                }),
              ],
            }),
          ],
        }),
      ],
    });
    const code = generateJavaScript(mod);
    expect(code).toContain("switch (role) {");
    expect(code).toContain('case "admin": {');
    expect(code).toContain("default: {");
  });

  it("should generate SET as const assignment", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "process",
          params: [],
          returnType: primitiveType("Void"),
          body: [set({ variable: "result", value: "42" })],
        }),
      ],
    });
    const code = generateJavaScript(mod);
    expect(code).toContain("const result = 42;");
  });

  it("should generate CALL as function call", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "process",
          params: [],
          returnType: primitiveType("Void"),
          body: [call({ target: "doWork", args: ["a", "b"] })],
        }),
      ],
    });
    const code = generateJavaScript(mod);
    expect(code).toContain("doWork(a, b);");
  });

  it("should generate FAIL as throw", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "process",
          params: [],
          returnType: primitiveType("Void"),
          body: [
            fail({ error: "NotFound", message: "User not found" }),
          ],
        }),
      ],
    });
    const code = generateJavaScript(mod);
    expect(code).toContain('throw new NotFoundError("User not found");');
  });

  it("should generate EMIT as emit call", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "process",
          params: [],
          returnType: primitiveType("Void"),
          body: [emit({ event: "Created", payload: "data" })],
        }),
      ],
    });
    const code = generateJavaScript(mod);
    expect(code).toContain('emit("Created", data);');
  });

  it("should generate RETRY as for loop with try/catch", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "process",
          params: [],
          returnType: primitiveType("Void"),
          body: [
            retry({
              target: "fetchData",
              attempts: 3,
              delay: "1s",
              onExhaust: [
                fail({
                  error: "ServiceUnavailable",
                  message: "Service down",
                }),
              ],
            }),
          ],
        }),
      ],
    });
    const code = generateJavaScript(mod);
    expect(code).toContain("for (let attempt = 1; attempt <= 3; attempt++)");
    expect(code).toContain("try {");
    expect(code).toContain("fetchData();");
    expect(code).toContain("} catch (error) {");
    expect(code).toContain("if (attempt === 3)");
    expect(code).toContain("// delay: 1s");
  });

  it("should generate comments", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "process",
          params: [],
          returnType: primitiveType("Void"),
          body: [comment({ text: "This is a comment" })],
        }),
      ],
    });
    const code = generateJavaScript(mod);
    expect(code).toContain("// This is a comment");
  });
});

// ---------------------------------------------------------------------------
// Snapshot: full module
// ---------------------------------------------------------------------------

describe("JavaScript Generator: snapshot", () => {
  it("should produce deterministic output for a full module", () => {
    const mod = buildSampleModule();
    const code = generateJavaScript(mod);

    // Determinism check
    const code2 = generateJavaScript(mod);
    expect(code).toBe(code2);

    // Structure checks
    expect(code).toContain("// Generated by CodeSpec — do not edit manually");
    expect(code).toContain("@typedef {Object} UserRegistrationInput");
    expect(code).toContain("@typedef {Object} UserRegistrationOutput");
    expect(code).toContain("export class EmailAlreadyExistsError extends Error {");
    expect(code).toContain("export function register(email, password) {");
    expect(code).toContain("@param {string} email");
    expect(code).toContain("@returns {User}");
  });

  it("should match snapshot", () => {
    const mod = buildSampleModule();
    const code = generateJavaScript(mod);
    expect(code).toMatchSnapshot();
  });
});
