import { describe, it, expect } from "vitest";
import { generatePhp } from "../../src/generator/php.js";
import {
  primitiveType,
  listType,
  mapType,
  namedType,
  optionalType,
  constraints,
  field,
  parameter,
  input,
  output,
  stateField,
  state,
  when,
  matchArm,
  match,
  set,
  call,
  returnNode,
  fail,
  emit,
  retry,
  limit,
  comment,
  action,
  invariantRule,
  invariants,
  errorDef,
  errors,
  dependencyDef,
  depends,
  module,
} from "../../src/ast/index.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Build a comprehensive sample module for snapshot testing. */
function buildSampleModule() {
  return module({
    name: "UserRegistration",
    members: [
      input({
        fields: [
          field({
            name: "email",
            fieldType: primitiveType("Email"),
            constraints: constraints({ format: "email" }),
          }),
          field({
            name: "password",
            fieldType: primitiveType("String"),
            constraints: constraints({ min: 8, max: 128 }),
          }),
          field({
            name: "nickname",
            fieldType: optionalType(primitiveType("String")),
          }),
        ],
      }),
      output({
        fields: [
          field({ name: "user", fieldType: namedType("User") }),
          field({ name: "token", fieldType: primitiveType("String") }),
        ],
      }),
      state({
        fields: [
          stateField({
            access: "READS",
            name: "users",
            fieldType: listType(namedType("User")),
          }),
          stateField({
            access: "WRITES",
            name: "sessions",
            fieldType: listType(namedType("Session")),
          }),
        ],
      }),
      errors({
        errors: [
          errorDef({
            name: "EmailAlreadyExists",
            status: 409,
            message: "A user with this email already exists",
          }),
          errorDef({
            name: "UserNotFound",
            status: 404,
            message: "The requested user was not found",
          }),
          errorDef({ name: "InternalError" }),
        ],
      }),
      action({
        name: "register",
        params: [
          parameter({ name: "email", paramType: primitiveType("Email") }),
          parameter({ name: "password", paramType: primitiveType("String") }),
        ],
        returnType: namedType("User"),
        body: [
          when({
            condition: "CALL userExists(email)",
            body: [
              fail({
                error: "EmailAlreadyExists",
                message: "A user with this email already exists",
              }),
            ],
          }),
          set({
            variable: "hashedPassword",
            value: "CALL hashPassword(password)",
          }),
          call({
            target: "createUser",
            args: ["email", "hashedPassword"],
            assignTo: "user",
          }),
          emit({ event: "UserRegistered", payload: "user" }),
          returnNode({ value: "user" }),
        ],
      }),
      invariants({
        rules: [
          invariantRule({
            kind: "ALWAYS",
            description: "Passwords are stored as hashed values",
          }),
          invariantRule({
            kind: "NEVER",
            description: "Email is shared without consent",
          }),
        ],
      }),
      depends({
        dependencies: [
          dependencyDef({
            name: "Database",
            description: "User persistence layer",
          }),
          dependencyDef({ name: "HashService" }),
        ],
      }),
    ],
  });
}

// ---------------------------------------------------------------------------
// Header & structure
// ---------------------------------------------------------------------------

describe("PHP Generator: header", () => {
  it("should include PHP opening tag and header comment", () => {
    const mod = module({ name: "Empty", members: [] });
    const code = generatePhp(mod);
    expect(code).toContain("<?php");
    expect(code).toContain("// Generated by CodeSpec — do not edit manually");
    expect(code).toContain("declare(strict_types=1);");
  });

  it("should generate a class with the module name", () => {
    const mod = module({ name: "UserService", members: [] });
    const code = generatePhp(mod);
    expect(code).toContain("class UserService");
    expect(code).toContain("{");
    expect(code).toContain("}");
  });
});

// ---------------------------------------------------------------------------
// Properties (from INPUT/OUTPUT)
// ---------------------------------------------------------------------------

describe("PHP Generator: properties", () => {
  it("should generate typed properties from INPUT fields", () => {
    const mod = module({
      name: "Login",
      members: [
        input({
          fields: [
            field({ name: "email", fieldType: primitiveType("Email") }),
            field({ name: "password", fieldType: primitiveType("String") }),
          ],
        }),
      ],
    });
    const code = generatePhp(mod);
    expect(code).toContain("public string $email;");
    expect(code).toContain("public string $password;");
  });

  it("should generate typed properties from OUTPUT fields", () => {
    const mod = module({
      name: "Login",
      members: [
        output({
          fields: [
            field({ name: "user", fieldType: namedType("User") }),
            field({ name: "token", fieldType: primitiveType("String") }),
          ],
        }),
      ],
    });
    const code = generatePhp(mod);
    expect(code).toContain("public User $user;");
    expect(code).toContain("public string $token;");
  });

  it("should handle optional types with nullable syntax", () => {
    const mod = module({
      name: "Profile",
      members: [
        input({
          fields: [
            field({
              name: "nickname",
              fieldType: optionalType(primitiveType("String")),
            }),
          ],
        }),
      ],
    });
    const code = generatePhp(mod);
    expect(code).toContain("public ?string $nickname;");
  });

  it("should map list types to array", () => {
    const mod = module({
      name: "Search",
      members: [
        output({
          fields: [
            field({
              name: "results",
              fieldType: listType(namedType("User")),
            }),
          ],
        }),
      ],
    });
    const code = generatePhp(mod);
    expect(code).toContain("public array $results;");
  });

  it("should map Map types to array", () => {
    const mod = module({
      name: "Config",
      members: [
        input({
          fields: [
            field({
              name: "settings",
              fieldType: mapType(
                primitiveType("String"),
                primitiveType("String"),
              ),
            }),
          ],
        }),
      ],
    });
    const code = generatePhp(mod);
    expect(code).toContain("public array $settings;");
  });
});

// ---------------------------------------------------------------------------
// Type mapping
// ---------------------------------------------------------------------------

describe("PHP Generator: type mapping", () => {
  it("should map all primitive types correctly", () => {
    const mod = module({
      name: "AllTypes",
      members: [
        input({
          fields: [
            field({ name: "s", fieldType: primitiveType("String") }),
            field({ name: "i", fieldType: primitiveType("Int") }),
            field({ name: "f", fieldType: primitiveType("Float") }),
            field({ name: "b", fieldType: primitiveType("Bool") }),
            field({ name: "d", fieldType: primitiveType("DateTime") }),
            field({ name: "e", fieldType: primitiveType("Email") }),
            field({ name: "h", fieldType: primitiveType("Hash") }),
            field({ name: "u", fieldType: primitiveType("UUID") }),
          ],
        }),
      ],
    });
    const code = generatePhp(mod);
    expect(code).toContain("public string $s;");
    expect(code).toContain("public int $i;");
    expect(code).toContain("public float $f;");
    expect(code).toContain("public bool $b;");
    expect(code).toContain("public \\DateTime $d;");
    expect(code).toContain("public string $e;");
    expect(code).toContain("public string $h;");
    expect(code).toContain("public string $u;");
  });
});

// ---------------------------------------------------------------------------
// Exception classes
// ---------------------------------------------------------------------------

describe("PHP Generator: exception classes", () => {
  it("should generate exception classes from ERRORS block", () => {
    const mod = module({
      name: "Test",
      members: [
        errors({
          errors: [
            errorDef({
              name: "NotFound",
              status: 404,
              message: "Not found",
            }),
            errorDef({ name: "InternalError" }),
          ],
        }),
      ],
    });
    const code = generatePhp(mod);
    expect(code).toContain(
      "class NotFoundException extends \\Exception",
    );
    expect(code).toContain("public int $status = 404;");
    expect(code).toContain("parent::__construct($message ?: 'Not found')");
    expect(code).toContain(
      "class InternalErrorException extends \\Exception",
    );
  });
});

// ---------------------------------------------------------------------------
// Method generation
// ---------------------------------------------------------------------------

describe("PHP Generator: methods", () => {
  it("should generate typed methods from ACTIONs", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "greet",
          params: [
            parameter({ name: "name", paramType: primitiveType("String") }),
          ],
          returnType: primitiveType("String"),
          body: [returnNode({ value: "name" })],
        }),
      ],
    });
    const code = generatePhp(mod);
    expect(code).toContain(
      "public function greet(string $name): string",
    );
    expect(code).toContain("return $name;");
  });

  it("should generate void return type", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "doNothing",
          params: [],
          returnType: primitiveType("Void"),
          body: [],
        }),
      ],
    });
    const code = generatePhp(mod);
    expect(code).toContain("public function doNothing(): void");
  });

  it("should handle nullable parameters", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "greet",
          params: [
            parameter({
              name: "name",
              paramType: optionalType(primitiveType("String")),
            }),
          ],
          returnType: primitiveType("Void"),
          body: [],
        }),
      ],
    });
    const code = generatePhp(mod);
    expect(code).toContain("?string $name");
  });
});

// ---------------------------------------------------------------------------
// Statement generation
// ---------------------------------------------------------------------------

describe("PHP Generator: statements", () => {
  it("should generate WHEN as if statement", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "check",
          params: [
            parameter({ name: "x", paramType: primitiveType("Int") }),
          ],
          returnType: primitiveType("String"),
          body: [
            when({
              condition: "x > 0",
              body: [returnNode({ value: "positive" })],
              otherwise: [returnNode({ value: "negative" })],
            }),
          ],
        }),
      ],
    });
    const code = generatePhp(mod);
    expect(code).toContain("if ($x > 0) {");
    expect(code).toContain("} else {");
  });

  it("should generate MATCH as switch statement", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "route",
          params: [
            parameter({ name: "role", paramType: primitiveType("String") }),
          ],
          returnType: primitiveType("Void"),
          body: [
            match({
              subject: "role",
              arms: [
                matchArm({
                  pattern: "admin",
                  body: [returnNode({ value: "panel" })],
                }),
                matchArm({
                  pattern: "_",
                  body: [returnNode({ value: "home" })],
                }),
              ],
            }),
          ],
        }),
      ],
    });
    const code = generatePhp(mod);
    expect(code).toContain("switch ($role) {");
    expect(code).toContain("case 'admin':");
    expect(code).toContain("default:");
    // break is omitted when arm body ends with return
    expect(code).not.toContain("break;");
  });

  it("should generate SET as variable assignment", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "process",
          params: [],
          returnType: primitiveType("Void"),
          body: [set({ variable: "result", value: "42" })],
        }),
      ],
    });
    const code = generatePhp(mod);
    expect(code).toContain("$result = 42;");
  });

  it("should generate CALL as method call with $this->", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "process",
          params: [],
          returnType: primitiveType("Void"),
          body: [call({ target: "doWork", args: ["a", "b"] })],
        }),
      ],
    });
    const code = generatePhp(mod);
    expect(code).toContain("$this->doWork($a, $b);");
  });

  it("should generate CALL with assignment", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "process",
          params: [],
          returnType: primitiveType("Void"),
          body: [
            call({
              target: "doWork",
              args: ["a", "b"],
              assignTo: "result",
            }),
          ],
        }),
      ],
    });
    const code = generatePhp(mod);
    expect(code).toContain("$result = $this->doWork($a, $b);");
  });

  it("should generate FAIL as throw", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "process",
          params: [],
          returnType: primitiveType("Void"),
          body: [
            fail({ error: "NotFound", message: "User not found" }),
          ],
        }),
      ],
    });
    const code = generatePhp(mod);
    expect(code).toContain(
      "throw new NotFoundException('User not found');",
    );
  });

  it("should generate FAIL without message", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "process",
          params: [],
          returnType: primitiveType("Void"),
          body: [fail({ error: "NotFound" })],
        }),
      ],
    });
    const code = generatePhp(mod);
    expect(code).toContain("throw new NotFoundException();");
  });

  it("should generate EMIT as method call", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "process",
          params: [],
          returnType: primitiveType("Void"),
          body: [
            emit({ event: "Created" }),
            emit({ event: "Updated", payload: "data" }),
          ],
        }),
      ],
    });
    const code = generatePhp(mod);
    expect(code).toContain("$this->emit('Created');");
    expect(code).toContain("$this->emit('Updated', $data);");
  });

  it("should generate RETRY as for loop with try/catch", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "process",
          params: [],
          returnType: primitiveType("Void"),
          body: [
            retry({
              target: "fetchData",
              attempts: 3,
              delay: "1s",
              onExhaust: [
                fail({
                  error: "ServiceUnavailable",
                  message: "Service down",
                }),
              ],
            }),
          ],
        }),
      ],
    });
    const code = generatePhp(mod);
    expect(code).toContain(
      "for ($attempt = 1; $attempt <= 3; $attempt++)",
    );
    expect(code).toContain("try {");
    expect(code).toContain("$this->fetchData();");
    expect(code).toContain("break;");
    expect(code).toContain("} catch (\\Exception $e) {");
    expect(code).toContain("if ($attempt === 3)");
    expect(code).toContain("// delay: 1s");
  });

  it("should generate LIMIT as rate limit check", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "api",
          params: [],
          returnType: primitiveType("Void"),
          body: [
            limit({
              rate: "100",
              per: "'minute'",
              onExceed: [
                fail({
                  error: "RateLimited",
                  message: "Too many requests",
                }),
              ],
            }),
          ],
        }),
      ],
    });
    const code = generatePhp(mod);
    expect(code).toContain("// LIMIT: 100 per");
    expect(code).toContain("if ($this->isRateLimitExceeded(100,");
    expect(code).toContain("throw new RateLimitedException");
  });

  it("should generate comments", () => {
    const mod = module({
      name: "Test",
      members: [
        action({
          name: "process",
          params: [],
          returnType: primitiveType("Void"),
          body: [comment({ text: "This is a comment" })],
        }),
      ],
    });
    const code = generatePhp(mod);
    expect(code).toContain("// This is a comment");
  });
});

// ---------------------------------------------------------------------------
// Snapshot: full module
// ---------------------------------------------------------------------------

describe("PHP Generator: snapshot", () => {
  it("should produce deterministic output for a full module", () => {
    const mod = buildSampleModule();
    const code = generatePhp(mod);

    // Determinism check
    const code2 = generatePhp(mod);
    expect(code).toBe(code2);

    // Structure checks
    expect(code).toContain("<?php");
    expect(code).toContain("// Generated by CodeSpec — do not edit manually");
    expect(code).toContain("declare(strict_types=1);");
    expect(code).toContain("class UserRegistration");
    expect(code).toContain("public string $email;");
    expect(code).toContain("public ?string $nickname;");
    expect(code).toContain("public User $user;");
    expect(code).toContain(
      "class EmailAlreadyExistsException extends \\Exception",
    );
    expect(code).toContain(
      "public function register(string $email, string $password): User",
    );
    expect(code).toContain("return $user;");
  });

  it("should match snapshot", () => {
    const mod = buildSampleModule();
    const code = generatePhp(mod);
    expect(code).toMatchSnapshot();
  });
});
