// ---------------------------------------------------------------------------
// CodeSpec PHP Generator
//
// Converts a CodeSpec AST (ModuleNode) into PHP 8+ source code.
// Generates a class with typed properties and methods.
// Deterministic: same AST always produces the same output.
// ---------------------------------------------------------------------------

import type {
  ModuleNode,
  ActionNode,
  FieldNode,
  ParameterNode,
  TypeReference,
  StatementNode,
  WhenNode,
  MatchNode,
  SetNode,
  CallNode,
  ReturnNode,
  FailNode,
  EmitNode,
  RetryNode,
  LimitNode,
  CommentNode,
  ErrorsNode,
  ErrorDef,
} from "../ast/nodes.js";

const HEADER = "// Generated by CodeSpec — do not edit manually";

// ---- Public API -----------------------------------------------------------

/**
 * Generate PHP 8+ source code from a CodeSpec ModuleNode.
 *
 * Produces a PHP class with typed properties for INPUT/OUTPUT fields and
 * typed methods for each ACTION. Exception classes are generated from
 * the ERRORS block.
 */
export function generatePhp(mod: ModuleNode): string {
  const parts: string[] = [];
  parts.push("<?php");
  parts.push(HEADER);
  parts.push("");
  parts.push("declare(strict_types=1);");
  parts.push("");

  // Generate exception classes from ERRORS block
  if (mod.errors) {
    parts.push(generateExceptionClasses(mod.errors));
    parts.push("");
  }

  // Generate the main class
  parts.push(`class ${mod.name}`);
  parts.push("{");

  const bodyParts: string[] = [];

  // Generate typed properties from INPUT fields
  if (mod.input) {
    for (const f of mod.input.fields) {
      bodyParts.push(generateProperty(f));
    }
  }

  // Generate typed properties from OUTPUT fields
  if (mod.output) {
    for (const f of mod.output.fields) {
      bodyParts.push(generateProperty(f));
    }
  }

  // Generate methods from ACTIONs
  for (const actionNode of mod.actions) {
    bodyParts.push(generateMethod(actionNode));
  }

  parts.push(bodyParts.join("\n\n"));
  parts.push("}");

  return parts.join("\n") + "\n";
}

// ---- Properties -----------------------------------------------------------

/**
 * Generate a typed PHP property declaration from a field.
 */
function generateProperty(f: FieldNode): string {
  const phpType = mapType(f.fieldType);
  const nullable = f.fieldType.kind === "optional" ? "?" : "";
  const baseType = f.fieldType.kind === "optional" ? mapType(f.fieldType.innerType) : phpType;
  return `    public ${nullable}${baseType} $${f.name};`;
}

// ---- Exception classes ----------------------------------------------------

/**
 * Generate PHP exception classes from an ERRORS block.
 */
function generateExceptionClasses(errorsNode: ErrorsNode): string {
  const lines: string[] = [];

  for (const err of errorsNode.errors) {
    lines.push(generateExceptionClass(err));
    lines.push("");
  }

  // Remove trailing empty line
  if (lines.length > 0 && lines[lines.length - 1] === "") {
    lines.pop();
  }

  return lines.join("\n");
}

/**
 * Generate a single PHP exception class with optional status and message.
 */
function generateExceptionClass(err: ErrorDef): string {
  const lines: string[] = [];
  lines.push(`class ${err.name}Exception extends \\Exception`);
  lines.push("{");
  if (err.status !== undefined) {
    lines.push(`    public int $status = ${String(err.status)};`);
    lines.push("");
  }
  lines.push("    public function __construct(string $message = \"\")");
  lines.push("    {");
  if (err.message !== undefined) {
    lines.push(
      `        parent::__construct($message ?: ${phpString(err.message)});`,
    );
  } else {
    lines.push(
      `        parent::__construct($message ?: ${phpString(err.name)});`,
    );
  }
  lines.push("    }");
  lines.push("}");
  return lines.join("\n");
}

// ---- Methods (ACTIONs) ----------------------------------------------------

/**
 * Generate a PHP method from an ACTION node.
 */
function generateMethod(actionNode: ActionNode): string {
  const params = actionNode.params.map(generateParam).join(", ");
  const returnType = mapType(actionNode.returnType);
  const lines: string[] = [];

  lines.push(
    `    public function ${actionNode.name}(${params}): ${returnType}`,
  );
  lines.push("    {");

  for (const stmt of actionNode.body) {
    lines.push(generateStatement(stmt, 2));
  }

  lines.push("    }");
  return lines.join("\n");
}

/**
 * Generate a typed PHP parameter string.
 */
function generateParam(param: ParameterNode): string {
  const phpType = param.paramType.kind === "optional"
    ? mapType(param.paramType.innerType)
    : mapType(param.paramType);
  const nullable = param.paramType.kind === "optional" ? "?" : "";
  return `${nullable}${phpType} $${param.name}`;
}

// ---- Statements -----------------------------------------------------------

/**
 * Generate PHP code for a statement node.
 */
function generateStatement(node: StatementNode, depth: number): string {
  switch (node.type) {
    case "When":
      return generateWhen(node, depth);
    case "Match":
      return generateMatch(node, depth);
    case "Set":
      return generateSet(node, depth);
    case "Call":
      return generateCall(node, depth);
    case "Return":
      return generateReturn(node, depth);
    case "Fail":
      return generateFail(node, depth);
    case "Emit":
      return generateEmit(node, depth);
    case "Retry":
      return generateRetry(node, depth);
    case "Limit":
      return generateLimit(node, depth);
    case "Comment":
      return generateComment(node, depth);
  }
}

/**
 * Generate an if/else from a WHEN/OTHERWISE node.
 */
function generateWhen(node: WhenNode, depth: number): string {
  const indent = makeIndent(depth);
  const lines: string[] = [];

  lines.push(`${indent}if (${node.condition}) {`);
  for (const stmt of node.body) {
    lines.push(generateStatement(stmt, depth + 1));
  }

  if (node.otherwise && node.otherwise.length > 0) {
    lines.push(`${indent}} else {`);
    for (const stmt of node.otherwise) {
      lines.push(generateStatement(stmt, depth + 1));
    }
  }

  lines.push(`${indent}}`);
  return lines.join("\n");
}

/**
 * Generate a match expression from a MATCH node (PHP 8 match).
 */
function generateMatch(node: MatchNode, depth: number): string {
  const indent = makeIndent(depth);
  const lines: string[] = [];

  lines.push(`${indent}switch ($${node.subject}) {`);

  for (const arm of node.arms) {
    if (arm.pattern === "_") {
      lines.push(`${indent}    default:`);
    } else {
      lines.push(`${indent}    case ${phpString(arm.pattern)}:`);
    }
    for (const stmt of arm.body) {
      lines.push(generateStatement(stmt, depth + 2));
    }
    lines.push(`${indent}        break;`);
  }

  lines.push(`${indent}}`);
  return lines.join("\n");
}

/**
 * Generate a variable assignment from a SET node.
 */
function generateSet(node: SetNode, depth: number): string {
  const indent = makeIndent(depth);
  return `${indent}$${node.variable} = ${node.value};`;
}

/**
 * Generate a function/method call from a CALL node.
 */
function generateCall(node: CallNode, depth: number): string {
  const indent = makeIndent(depth);
  const args = node.args.map((a) => `$${a}`).join(", ");
  if (node.assignTo) {
    return `${indent}$${node.assignTo} = $this->${node.target}(${args});`;
  }
  return `${indent}$this->${node.target}(${args});`;
}

/**
 * Generate a return statement from a RETURN node.
 */
function generateReturn(node: ReturnNode, depth: number): string {
  const indent = makeIndent(depth);
  return `${indent}return $${node.value};`;
}

/**
 * Generate a throw statement from a FAIL node.
 */
function generateFail(node: FailNode, depth: number): string {
  const indent = makeIndent(depth);
  if (node.message) {
    return `${indent}throw new ${node.error}Exception(${phpString(node.message)});`;
  }
  return `${indent}throw new ${node.error}Exception();`;
}

/**
 * Generate an emit call from an EMIT node.
 */
function generateEmit(node: EmitNode, depth: number): string {
  const indent = makeIndent(depth);
  if (node.payload) {
    return `${indent}$this->emit(${phpString(node.event)}, $${node.payload});`;
  }
  return `${indent}$this->emit(${phpString(node.event)});`;
}

/**
 * Generate a try/catch with retry loop from a RETRY node.
 */
function generateRetry(node: RetryNode, depth: number): string {
  const indent = makeIndent(depth);
  const lines: string[] = [];

  lines.push(`${indent}for ($attempt = 1; $attempt <= ${String(node.attempts)}; $attempt++) {`);
  lines.push(`${indent}    try {`);
  lines.push(`${indent}        $this->${node.target}();`);
  lines.push(`${indent}        break;`);
  lines.push(`${indent}    } catch (\\Exception $e) {`);
  lines.push(`${indent}        if ($attempt === ${String(node.attempts)}) {`);

  for (const stmt of node.onExhaust) {
    lines.push(generateStatement(stmt, depth + 3));
  }

  lines.push(`${indent}        }`);

  if (node.delay) {
    lines.push(`${indent}        // delay: ${node.delay}`);
  }

  lines.push(`${indent}    }`);
  lines.push(`${indent}}`);
  return lines.join("\n");
}

/**
 * Generate rate limiting logic from a LIMIT node.
 */
function generateLimit(node: LimitNode, depth: number): string {
  const indent = makeIndent(depth);
  const lines: string[] = [];

  lines.push(`${indent}// LIMIT: ${node.rate} per ${node.per}`);
  lines.push(`${indent}if ($this->isRateLimitExceeded(${node.rate}, ${node.per})) {`);

  for (const stmt of node.onExceed) {
    lines.push(generateStatement(stmt, depth + 1));
  }

  lines.push(`${indent}}`);
  return lines.join("\n");
}

/**
 * Generate a comment from a Comment node.
 */
function generateComment(node: CommentNode, depth: number): string {
  const indent = makeIndent(depth);
  return `${indent}// ${node.text}`;
}

// ---- Type mapping ---------------------------------------------------------

/**
 * Map a CodeSpec TypeReference to a PHP type string.
 */
function mapType(typeRef: TypeReference): string {
  switch (typeRef.kind) {
    case "primitive":
      return mapPrimitive(typeRef.name);
    case "list":
      return "array";
    case "map":
      return "array";
    case "named":
      return typeRef.name;
    case "optional":
      return `?${mapType(typeRef.innerType)}`;
  }
}

/**
 * Map a CodeSpec primitive type name to a PHP type.
 */
function mapPrimitive(name: string): string {
  switch (name) {
    case "String":
      return "string";
    case "Int":
      return "int";
    case "Float":
      return "float";
    case "Bool":
      return "bool";
    case "DateTime":
      return "\\DateTime";
    case "Email":
      return "string";
    case "Hash":
      return "string";
    case "UUID":
      return "string";
    case "Void":
      return "void";
    default:
      return name;
  }
}

// ---- Helpers --------------------------------------------------------------

/**
 * Create a 4-space indentation string for the given nesting depth.
 */
function makeIndent(depth: number): string {
  return "    ".repeat(depth);
}

/**
 * Escape a string value for PHP output, wrapping it in single quotes.
 */
function phpString(value: string): string {
  const escaped = value.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
  return `'${escaped}'`;
}
