// ---------------------------------------------------------------------------
// CodeSpec TypeScript Generator
//
// Converts a CodeSpec AST (ModuleNode) into TypeScript source code.
// Deterministic: same AST always produces the same output.
// ---------------------------------------------------------------------------

import type {
  ModuleNode,
  InputNode,
  OutputNode,
  ActionNode,
  FieldNode,
  ParameterNode,
  TypeReference,
  StatementNode,
  WhenNode,
  MatchNode,
  SetNode,
  CallNode,
  ReturnNode,
  FailNode,
  EmitNode,
  RetryNode,
  LimitNode,
  CommentNode,
  ErrorsNode,
  ErrorDef,
} from "../ast/nodes.js";

const HEADER = "// Generated by CodeSpec — do not edit manually";

// ---- Public API -----------------------------------------------------------

/**
 * Generate TypeScript source code from a CodeSpec ModuleNode.
 *
 * Produces typed interfaces for INPUT/OUTPUT blocks and typed functions for
 * each ACTION. Error classes are generated from the ERRORS block.
 */
export function generateTypeScript(mod: ModuleNode): string {
  const parts: string[] = [];
  parts.push(HEADER);
  parts.push("");

  // Generate error classes from ERRORS block
  if (mod.errors) {
    parts.push(generateErrorClasses(mod.errors));
    parts.push("");
  }

  // Generate INPUT interface
  if (mod.input) {
    parts.push(generateInterface(mod.name, "Input", mod.input));
    parts.push("");
  }

  // Generate OUTPUT interface
  if (mod.output) {
    parts.push(generateInterface(mod.name, "Output", mod.output));
    parts.push("");
  }

  // Generate ACTION functions
  for (const actionNode of mod.actions) {
    parts.push(generateFunction(actionNode));
    parts.push("");
  }

  return parts.join("\n").trimEnd() + "\n";
}

// ---- Interfaces -----------------------------------------------------------

/**
 * Generate a TypeScript interface from an INPUT or OUTPUT block.
 */
function generateInterface(
  moduleName: string,
  blockName: string,
  node: InputNode | OutputNode,
): string {
  const interfaceName = `${moduleName}${blockName}`;
  const lines: string[] = [];
  lines.push(`export interface ${interfaceName} {`);

  for (const f of node.fields) {
    lines.push(generateFieldDeclaration(f));
  }

  lines.push("}");
  return lines.join("\n");
}

/**
 * Generate a single interface field declaration.
 */
function generateFieldDeclaration(f: FieldNode): string {
  const tsType = mapType(f.fieldType);
  const optional = f.fieldType.kind === "optional" ? "?" : "";
  const baseType = f.fieldType.kind === "optional" ? mapType(f.fieldType.innerType) : tsType;
  return `  ${f.name}${optional}: ${baseType};`;
}

// ---- Error classes --------------------------------------------------------

/**
 * Generate TypeScript error classes from an ERRORS block.
 */
function generateErrorClasses(errorsNode: ErrorsNode): string {
  const lines: string[] = [];

  for (const err of errorsNode.errors) {
    lines.push(generateErrorClass(err));
    lines.push("");
  }

  // Remove trailing empty line
  if (lines.length > 0 && lines[lines.length - 1] === "") {
    lines.pop();
  }

  return lines.join("\n");
}

/**
 * Generate a single error class with optional status and message.
 */
function generateErrorClass(err: ErrorDef): string {
  const lines: string[] = [];
  lines.push(`export class ${err.name}Error extends Error {`);
  if (err.status !== undefined) {
    lines.push(`  public readonly status = ${String(err.status)};`);
  }
  lines.push("");
  lines.push("  constructor(message?: string) {");
  if (err.message !== undefined) {
    lines.push(`    super(message ?? ${JSON.stringify(err.message)});`);
  } else {
    lines.push(`    super(message ?? ${JSON.stringify(err.name)});`);
  }
  lines.push(`    this.name = ${JSON.stringify(err.name + "Error")};`);
  lines.push("  }");
  lines.push("}");
  return lines.join("\n");
}

// ---- Functions (ACTIONs) --------------------------------------------------

/**
 * Generate a TypeScript function from an ACTION node.
 */
function generateFunction(actionNode: ActionNode): string {
  const params = actionNode.params.map(generateParam).join(", ");
  const returnType = mapType(actionNode.returnType);
  const lines: string[] = [];

  lines.push(
    `export function ${actionNode.name}(${params}): ${returnType} {`,
  );

  for (const stmt of actionNode.body) {
    const stmtLines = generateStatement(stmt, 1);
    lines.push(stmtLines);
  }

  lines.push("}");
  return lines.join("\n");
}

/**
 * Generate a typed parameter string.
 */
function generateParam(param: ParameterNode): string {
  const tsType = param.paramType.kind === "optional"
    ? mapType(param.paramType.innerType)
    : mapType(param.paramType);
  const optional = param.paramType.kind === "optional" ? "?" : "";
  return `${param.name}${optional}: ${tsType}`;
}

// ---- Statements -----------------------------------------------------------

/**
 * Generate TypeScript code for a statement node.
 */
function generateStatement(node: StatementNode, depth: number): string {
  switch (node.type) {
    case "When":
      return generateWhen(node, depth);
    case "Match":
      return generateMatch(node, depth);
    case "Set":
      return generateSet(node, depth);
    case "Call":
      return generateCall(node, depth);
    case "Return":
      return generateReturn(node, depth);
    case "Fail":
      return generateFail(node, depth);
    case "Emit":
      return generateEmit(node, depth);
    case "Retry":
      return generateRetry(node, depth);
    case "Limit":
      return generateLimit(node, depth);
    case "Comment":
      return generateComment(node, depth);
  }
}

/**
 * Generate an if/else from a WHEN/OTHERWISE node.
 */
function generateWhen(node: WhenNode, depth: number): string {
  const indent = makeIndent(depth);
  const lines: string[] = [];

  lines.push(`${indent}if (${node.condition}) {`);
  for (const stmt of node.body) {
    lines.push(generateStatement(stmt, depth + 1));
  }

  if (node.otherwise && node.otherwise.length > 0) {
    lines.push(`${indent}} else {`);
    for (const stmt of node.otherwise) {
      lines.push(generateStatement(stmt, depth + 1));
    }
  }

  lines.push(`${indent}}`);
  return lines.join("\n");
}

/**
 * Generate a switch statement from a MATCH node.
 */
function generateMatch(node: MatchNode, depth: number): string {
  const indent = makeIndent(depth);
  const lines: string[] = [];

  lines.push(`${indent}switch (${node.subject}) {`);

  for (const arm of node.arms) {
    if (arm.pattern === "_") {
      lines.push(`${indent}  default: {`);
    } else {
      lines.push(`${indent}  case ${JSON.stringify(arm.pattern)}: {`);
    }
    for (const stmt of arm.body) {
      lines.push(generateStatement(stmt, depth + 2));
    }
    if (!bodyEndsWithExit(arm.body)) {
      lines.push(`${indent}    break;`);
    }
    lines.push(`${indent}  }`);
  }

  lines.push(`${indent}}`);
  return lines.join("\n");
}

/**
 * Generate a const assignment from a SET node.
 */
function generateSet(node: SetNode, depth: number): string {
  const indent = makeIndent(depth);
  return `${indent}const ${node.variable} = ${node.value};`;
}

/**
 * Generate a function call from a CALL node.
 */
function generateCall(node: CallNode, depth: number): string {
  const indent = makeIndent(depth);
  const args = node.args.join(", ");
  if (node.assignTo) {
    return `${indent}const ${node.assignTo} = ${node.target}(${args});`;
  }
  return `${indent}${node.target}(${args});`;
}

/**
 * Generate a return statement from a RETURN node.
 */
function generateReturn(node: ReturnNode, depth: number): string {
  const indent = makeIndent(depth);
  return `${indent}return ${node.value};`;
}

/**
 * Generate a throw statement from a FAIL node.
 */
function generateFail(node: FailNode, depth: number): string {
  const indent = makeIndent(depth);
  const className = mapErrorName(node.error);
  if (node.message) {
    return `${indent}throw new ${className}(${JSON.stringify(node.message)});`;
  }
  return `${indent}throw new ${className}();`;
}

/** Map a CodeSpec error name to a TypeScript error class. */
function mapErrorName(name: string): string {
  // Map well-known exception names from other languages to JS built-ins
  const mapping: Record<string, string> = {
    "Exception": "Error",
    "RuntimeException": "Error",
    "LogicException": "Error",
    "InvalidArgumentException": "TypeError",
    "RangeException": "RangeError",
    "OverflowException": "RangeError",
    "UnderflowException": "RangeError",
    "TypeError": "TypeError",
    "RangeError": "RangeError",
  };
  if (mapping[name]) return mapping[name];
  // Already ends with Error — use as-is
  if (name.endsWith("Error")) return name;
  // Ends with Exception — convert to Error suffix
  if (name.endsWith("Exception")) return name.replace(/Exception$/, "Error");
  // Otherwise append Error
  return `${name}Error`;
}

/**
 * Generate an emit call from an EMIT node.
 */
function generateEmit(node: EmitNode, depth: number): string {
  const indent = makeIndent(depth);
  if (node.payload) {
    return `${indent}emit(${JSON.stringify(node.event)}, ${node.payload});`;
  }
  return `${indent}emit(${JSON.stringify(node.event)});`;
}

/**
 * Generate a try/catch with retry loop from a RETRY node.
 */
function generateRetry(node: RetryNode, depth: number): string {
  const indent = makeIndent(depth);
  const lines: string[] = [];

  lines.push(`${indent}for (let attempt = 1; attempt <= ${String(node.attempts)}; attempt++) {`);
  lines.push(`${indent}  try {`);
  lines.push(`${indent}    ${node.target}();`);
  lines.push(`${indent}    break;`);
  lines.push(`${indent}  } catch (error) {`);
  lines.push(`${indent}    if (attempt === ${String(node.attempts)}) {`);

  for (const stmt of node.onExhaust) {
    lines.push(generateStatement(stmt, depth + 3));
  }

  lines.push(`${indent}    }`);

  if (node.delay) {
    lines.push(`${indent}    // delay: ${node.delay}`);
  }

  lines.push(`${indent}  }`);
  lines.push(`${indent}}`);
  return lines.join("\n");
}

/**
 * Generate rate limiting logic from a LIMIT node.
 */
function generateLimit(node: LimitNode, depth: number): string {
  const indent = makeIndent(depth);
  const lines: string[] = [];

  lines.push(`${indent}// LIMIT: ${node.rate} per ${node.per}`);
  lines.push(`${indent}if (isRateLimitExceeded(${node.rate}, ${node.per})) {`);

  for (const stmt of node.onExceed) {
    lines.push(generateStatement(stmt, depth + 1));
  }

  lines.push(`${indent}}`);
  return lines.join("\n");
}

/**
 * Generate a comment from a Comment node.
 */
function generateComment(node: CommentNode, depth: number): string {
  const indent = makeIndent(depth);
  return `${indent}// ${node.text}`;
}

// ---- Type mapping ---------------------------------------------------------

/**
 * Map a CodeSpec TypeReference to a TypeScript type string.
 */
function mapType(typeRef: TypeReference): string {
  switch (typeRef.kind) {
    case "primitive":
      return mapPrimitive(typeRef.name);
    case "list":
      return `${mapType(typeRef.elementType)}[]`;
    case "map":
      return `Map<${mapType(typeRef.keyType)}, ${mapType(typeRef.valueType)}>`;
    case "named":
      return typeRef.name;
    case "optional":
      return `${mapType(typeRef.innerType)} | undefined`;
  }
}

/**
 * Map a CodeSpec primitive type name to a TypeScript type.
 */
function mapPrimitive(name: string): string {
  switch (name) {
    case "String":
      return "string";
    case "Int":
      return "number";
    case "Float":
      return "number";
    case "Bool":
      return "boolean";
    case "DateTime":
      return "Date";
    case "Email":
      return "string";
    case "Hash":
      return "string";
    case "UUID":
      return "string";
    case "Void":
      return "void";
    default:
      return name;
  }
}

// ---- Helpers --------------------------------------------------------------

/** Check whether a statement list ends with a return or throw (no break needed). */
function bodyEndsWithExit(body: readonly StatementNode[]): boolean {
  if (body.length === 0) return false;
  const last = body[body.length - 1];
  return last.type === "Return" || last.type === "Fail";
}

/**
 * Create a 2-space indentation string for the given nesting depth.
 */
function makeIndent(depth: number): string {
  return "  ".repeat(depth);
}
